### ISSUE TITLE
バージョンを削除すると割り当てたテストケースが削除される

### ISSUE THREAD

**Issue by naitoh** [kawasima/redmine_impasse#104]
Impasse は仕様上、Redmineのバージョンが必須の作りになっておりますが、間違ってバージョンを削除すると割り当てたテスト計画も一緒に削除されてしまいます。

同様のケースで、Redmineのチケットの振る舞いはバージョンに括り付けられたチケットが一つでも存在するとバージョンは削除不可です。

安全性のため、バージョンに括り付けられたテスト計画が存在する場合、同様にバージョンを削除不可にできないでしょうか？

**Comment by kawasima** [comment]
なるほど。ありがとうございます。
次のバージョンで対応します！
