### ISSUE TITLE
Error during plugin migration on Redmine 2.0.3

### ISSUE THREAD

**Issue by daest** [kawasima/redmine_impasse#120]
By executing rake redmine:plugins:migrate RAILS_ENV=production, I following error is thrown:

... /plugins/redmine_impasse/lib/impasse_hooks.rb:94: syntax error, unexpected '}', expecting keyword_end
...nditions => {:bug_id, issue.id})
...                                                      ^

**Comment by kawasima** [comment]
It's my awful mistake. I fixed it in #119.
I'll release the fixed version soon.
