### ISSUE TITLE
Calling set_table_name is deprecated (Redmine 2.0)

### ISSUE THREAD

**Issue by lav45** [kawasima/redmine_impasse#125]
Redmine 2.0
With adding tasks

Started POST "/projects/pricefactor/issues" for 193.58.255.3 at Thu Sep 13 20:32:03 +0300 2012
Processing by IssuesController#create as HTML
  Parameters: {"commit"=>"Создать", "project_id"=>"pricefactor", "authenticity_token"=>"6s95La+jC5yT+ghVA2IqhFI8D3Z/igmd14Jzm/E8+B8=", "utf8"=>"✓", "issue"=$
DEPRECATION WARNING: Calling set_table_name is deprecated. Please use `self.table_name = 'the_name'` instead. (called from /var/www/arno/www/plugins/redmine$
Completed 500 Internal Server Error in 468ms

NoMethodError (undefined method `requirement_tracker' for nil:NilClass):
  lib/redmine/hook.rb:61:in`send'
  lib/redmine/hook.rb:61:in `call_hook'
  lib/redmine/hook.rb:61:in`each'
  lib/redmine/hook.rb:61:in `call_hook'
  lib/redmine/hook.rb:58:in`tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:153:in`call_hook'
  app/controllers/issues_controller.rb:149:in `create'

**Comment by kawasima** [comment]
I fixed it at version 1.2.2.
