### ISSUE TITLE
undefined method for labelled_tabular_form_for

### ISSUE THREAD

**Issue by hugh-barclay** [kawasima/redmine_impasse#127]
I'm running 2.1.0.stable.10431
Ruby 1.9.3p194

Following is Gem List:
actionmailer (3.2.8)
actionpack (3.2.8)
activemodel (3.2.8)
activerecord (3.2.8)
activerecord-mysql2-adapter (0.0.3)
activeresource (3.2.8)
activesupport (3.2.8)
arel (3.0.2)
builder (3.1.3, 3.0.3, 3.0.0)
bundler (1.2.0)
coderay (1.0.7, 1.0.6)
daemon_controller (1.0.0)
erubis (2.7.0)
fastercsv (1.5.0)
fastthread (1.0.7)
ffi (1.1.5)
hike (1.2.1)
i18n (0.6.1)
journey (1.0.4)
jquery-rails (2.1.2, 2.0.3, 2.0.2)
json (1.7.5)
mail (2.4.4)
metaclass (0.0.1)
mime-types (1.19)
mocha (0.12.4, 0.12.3)
multi_json (1.3.6)
mysql (2.8.1)
mysql2 (0.3.11)
net-ldap (0.3.1)
nokogiri (1.4.2)
passenger (3.0.17)
polyglot (0.3.3)
rack (1.4.1)
rack-cache (1.2)
rack-openid (1.3.1)
rack-ssl (1.3.2)
rack-test (0.6.1)
rails (3.2.8)
railties (3.2.8)
rake (0.9.2.2)
rdoc (3.12)
rmagick (2.13.1)
ruby-openid (2.2.0, 2.1.8, 2.1.4)
rubygems-bundler (1.1.0)
rvm (1.11.3.5)
simple_enum (1.6.3)
sprockets (2.1.3)
sqlite3 (1.3.6)
svn (0.2.0)
thor (0.16.0)
tilt (1.3.3)
treetop (1.4.10)
tzinfo (0.3.33)
uuidtools (2.1.1)
xapian-full (1.2.3)
zip (2.0.2)

The error is:

Started GET "/redmine/projects/<projectnamehere>/impasse/test_case" for at 2012-09-24 14:23:09 +1000 
Processing by ImpasseTestCaseController#index as HTML
  Parameters: {"project_id"=>"<projectnamehere>"}
  Current user: admin (id=1)
DEPRECATION WARNING: Calling set_table_name is deprecated. Please use `self.table_name = 'the_name'` instead. (called from class:Node at /usr/share/redmine/plugins/redmine_impasse/app/models/impasse/node.rb:4)
DEPRECATION WARNING: Calling set_table_name is deprecated. Please use `self.table_name = 'the_name'` instead. (called from class:Setting at /usr/share/redmine/plugins/redmine_impasse/app/models/impasse/setting.rb:4)
  Rendered plugins/redmine_impasse/app/views/impasse_test_case/index.html.erb within layouts/base (4781.6ms)
Completed 500 Internal Server Error in 4970ms

ActionView::Template::Error (undefined method `labelled_tabular_form_for' for #<#<Class:0xc3ca56c>:0xc3c713c>):
    103:        </p>
    104:      <% end %>
    105:    <% else %>
    106:           <% output = labelled_tabular_form_for @project, :as => :copy_tests, :url => { :action => :copy_to_another_project } do |f| %>
    107:        <p>
    108:          <label for="dest_project_id"><%= l(:field_project) %></label>
    109:          <%= select_tag('dest_project_id', project_tree_options_for_select(@allowed_projects, :selected => @target_project)) %>
  plugins/redmine_impasse/app/views/impasse_test_case/index.html.erb:106:in`_plugins_redmine_impasse_app_views_impasse_test_case_index_html_erb___607143658_91763460'

**Comment by luisfgfurtado** [comment]
First of all, congratulations for your project.
I´m looking forward for 1.2.3 release!
For while I'm applying these fixes manually.
