### ISSUE TITLE
Steps Order

### ISSUE THREAD

**Issue by ricardobauqa** [kawasima/redmine_impasse#134]
Hi Kawasima, 

I found a error in Impasse when creat a test case the steps order is displayed inverted  as 4,3,2,1  to reorder I need update the test case

**Comment by kawasima** [comment]
It's a specification, now.
But since it's slightly confusing interface, I'll make it understandable in the future version.

**Comment by k-minemoto** [comment]
fixes #153 fixes #151 fixes #134 5e8c4f11e964649abc5bec85a052fa81a9cd3284
