### ISSUE TITLE
create new test plan with IE9 and no version produce redmine 500 error

### ISSUE THREAD

**Issue by halimali** [kawasima/redmine_impasse#138]
First of all, thanks for the great plugin.

If we create a test plan and there is no version exist in the project, and then press the create button,
the "please select an item" popup  will appear on Chrome browser.

However,  I am using IE9 no such popup will appear and redmine 500 error will appear. I am using Redmine V2.1.0

Below is log/production.log output.

Started POST "/projects/test_test_case_2/impasse/test_plans/new" for 10.1.10.127 at Tue Oct 16 18:29:10 +0800 2012
Processing by ImpasseTestPlansController#new as HTML
  Parameters: {"test_plan"=>{"name"=>"test test plan", "notes"=>""}, "commit"=>"Create", "project_id"=>"test_test_case_2", "authenticity_token"=>"ssdffsdfdfsfsfsXFDFSDFDSFDSFSDFS=", "utf8"=>"â"}
  Current user: halim (id=1)
Completed 500 Internal Server Error in 43ms

ActiveRecord::StatementInvalid (Mysql::Error: Column 'version_id' cannot be null: INSERT INTO `impasse_test_plans` (`active`, `name`, `notes`, `version_id`) VALUES (?, ?, ?, ?)):

**Comment by halimali** [comment]
I have resolve this and push it to my repository.
Please view the commit at https://github.com/halimali/redmine_impasse/commit/803dcce195d8f0dd5fc3619604faa441e7c5c185

I am unsure this is the optimal way to resolve the issue. Please review.

**Comment by k-minemoto** [comment]
same issue #142
