### ISSUE TITLE
deleting the wrong table in create_impasse_requirements_cases.rb

### ISSUE THREAD

**Issue by lokisite** [kawasima/redmine_impasse#141]
You're deleting the wrong table in create_impasse_requirements_cases.rb.  This breaks the uninstall.

class CreateImpasseRequirementCases < ActiveRecord::Migration
  def self.up
    create_table :impasse_requirement_cases do |t|
      t.column :requirement_id, :integer, :null => false
      t.column :test_case_id, :integer, :null => false
    end
  end

  def self.down
    drop_table :impasse_requirement_issues
  end
end

**Comment by kawasima** [comment]
Oh, it's my mistake. Thank you.
