### ISSUE TITLE
別プロジェクトへのマスタケースコピーが動作しない

### ISSUE THREAD

**Issue by komi** [kawasima/redmine_impasse#148]
先日対面でお話した、テストケースをチェックし、プロジェクト選択後、「コピー」を押下しても何も動作しないという事象です。
検出者によると、ブラウザはChrome、IE8。リクエストは届いていなかったと思う、とのことです。

**Comment by k-minemoto** [comment]
impasse 1.2.2 (develop branch)
で見ていますが、これも再現できませんでした。

Chromeの場合、F12を押すと立ち上がるDeveloper Toolsで、[テスト]タブを押してからコピーを
完了するまでの間で、次の事象が起こっていないか見て頂けますか？
・Consoleにエラーが出ている
　→この場合、出ている内容を教えて下さい。
・Networkで、Statusが200、302、304以外がある
　→この場合も、出ているStatusの値と、可能であればレスポンスのHeaderも教えて下さい。

**Comment by kawasima** [comment]
Redmineのバージョンによってtabular_form_for がid属性をつけたり、付けなかったりするようで、それが原因でJQueryのイベントが発火しないもようです。
なので、formに明示的にid属性を付けるように修正します。
