### ISSUE TITLE
Internal error Redmine 2.1.2

### ISSUE THREAD

**Issue by boot2linux** [kawasima/redmine_impasse#150]
On clicking Tests Table, internal error is reported. The following is log:

Started GET "/projects/usi/impasse/test_case" for 127.0.0.1 at Tue Oct 23 10:14:37 +0800 2012
Processing by ImpasseTestCaseController#index as HTML
  Parameters: {"project_id"=>"usi"}
  Current user: michael (id=13)
  Rendered plugins/redmine_impasse/app/views/impasse_test_case/index.html.erb within layouts/base (1216.8ms)
Completed 500 Internal Server Error in 1240ms

ActionView::Template::Error (undefined method `labelled_tabular_form_for' for #<#<Class:0xb5a1b3e0>:0xb4435a94>):
    103:        </p>
    104:      <% end %>
    105:    <% else %>
    106:           <% output = labelled_tabular_form_for @project, :as => :copy_tests, :url => { :action => :copy_to_another_project } do |f| %>
    107:        <p>
    108:          <label for="dest_project_id"><%= l(:field_project) %></label>
    109:          <%= select_tag('dest_project_id', project_tree_options_for_select(@allowed_projects, :selected => @target_project)) %>
  plugins/redmine_impasse/app/views/impasse_test_case/index.html.erb:106:in`_plugins_redmine_impasse_app_views_impasse_test_case_index_html_erb___621823703__624087438'
  actionpack (3.2.8) lib/action_view/template.rb:145:in `send'
  actionpack (3.2.8) lib/action_view/template.rb:145:in`render'
  activesupport (3.2.8) lib/active_support/notifications.rb:125:in `instrument'
  actionpack (3.2.8) lib/action_view/template.rb:143:in`render'
  actionpack (3.2.8) lib/action_view/renderer/template_renderer.rb:47:in `render_template'
  actionpack (3.2.8) lib/action_view/renderer/abstract_renderer.rb:38:in`instrument'
  activesupport (3.2.8) lib/active_support/notifications.rb:123:in `instrument'
  activesupport (3.2.8) lib/active_support/notifications/instrumenter.rb:20:in`instrument'
  activesupport (3.2.8) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.8) lib/action_view/renderer/abstract_renderer.rb:38:in`instrument'
  actionpack (3.2.8) lib/action_view/renderer/template_renderer.rb:46:in `render_template'
  actionpack (3.2.8) lib/action_view/renderer/template_renderer.rb:54:in`render_with_layout'
  actionpack (3.2.8) lib/action_view/renderer/template_renderer.rb:45:in `render_template'
... ...

**Comment by halimali** [comment]
You will need to checkout the hotfix/1.2.3 that resolves the issue.

**Comment by boot2linux** [comment]
Dear halimali,
thank your very much! It works now.
