### ISSUE TITLE
Test case steps change order

### ISSUE THREAD

**Issue by lazetics** [kawasima/redmine_impasse#151]
When edit a test case that conatins 10 or more steps, after saving it the order of steps is changed. In particular, steps with the step number bigger than 9 are displayed before other steps. E.g. if I have 14 steps they are displayed as 10, 11, 12, 13, 14, 1, 2 ... 9. I checked the database, every time a test case is updated the ids of the steps are put at the end of the auto increment sequence.

**Comment by rafaelmatuo** [comment]
this also happens with me, but if you "Refresh" the test case, resolve the issue, you can see it in #134

**Comment by k-minemoto** [comment]
fixes #153 fixes #151 fixes #134 5e8c4f11e964649abc5bec85a052fa81a9cd3284
