### ISSUE TITLE
作成したテストケースのステップがstep-order順に表示されない。

### ISSUE THREAD

**Issue by hondaYoshitaka** [kawasima/redmine_impasse#153]
◆概要
作成したテストケースのステップがstep-order順に表示されない。

◆場所
テスト » テスト計画の一覧 » 実行

◆再現条件
1. テスト » テスト計画の一覧 » 実行に遷移する
2. 作成したテストケースを開き、ステップ欄を確認する
 → 順序が 4>2>1>3 などばらばらになっている。

**Comment by k-minemoto** [comment]
fixes #153 fixes #151 fixes #134 5e8c4f11e964649abc5bec85a052fa81a9cd3284
