### ISSUE TITLE
Its not possible to scroll down with a lot steps

### ISSUE THREAD

**Issue by rafaelmatuo** [kawasima/redmine_impasse#155]
When you try to execute a test with a lot of steps its not possible to scroll down to "Save" the test, you need to press F11, to see all the test display box and to acess the "Save" button

**Comment by k-minemoto** [comment]
I tested both Firefox16.0.2 and IE9. 
The scroll bar was displayed and both of the browsers were able to push "Save" button. 
What browser did you used?

**Comment by rafaelmatuo** [comment]
I tested in chrome, IE8 and Firefox16.0.2 and happens. but you need to put long steps, my steps are (that happens the bug):

Actions  
1- Open the application  
2- A pop up informing about the trial limited time to play will be displayed (usually 10min), select the trial option
3- Play for 1 min and exit the game
4- Open the application and play 2 min and exit again
5- Open and play 3 min, close the game
6- Play until reach the trial limited time

Expect behavior
1- Application's name must be shown properly
2- Application's name must be shown properly
3- Application's name must be shown properly
4- Application's name must be shown properly
5- Application's name must be shown properly
6- When you do not play more than 10 min, it must be possible to start playing again. 2. When you play for more than 10min, if you try to play the game again it should ask to purchase the game. 3. If you keep playing without closing the game, it's possible to play more than 10min. 4. When you are testing in Wi-Fi's Models, must be not show to buy by carrier (SMS or Credit carrier), usually appears only Credit Card.
