### ISSUE TITLE
Still getting "labelled_tabular_form_for"

### ISSUE THREAD

**Issue by marceloanabuki** [kawasima/redmine_impasse#156]
Hello,

I just installed the latest version with git clone and I am getting the following error when I try to use the feature.

I am using redming 2.1.2. 

Appreciate the help.

ActionView::Template::Error (undefined method `labelled_tabular_form_for' for #<#<Class:0x2add828b0878>:0x2add8285a0b8>):
    103:            </p>
    104:          <% end %>
    105:        <% else %>
    106:           <% output = labelled_tabular_form_for @project, :as => :copy_tests, :url => { :action => :copy_to_another_project } do |f| %>
    107:            <p>
    108:              <label for="dest_project_id"><%= l(:field_project) %></label>
    109:              <%= select_tag('dest_project_id', project_tree_options_for_select(@allowed_projects, :selected => @target_project)) %>
  plugins/redmine_impasse/app/views/impasse_test_case/index.html.erb:106:in`_plugins_redmine_impasse_app_views_impasse_test_case_index_html_erb___1209805012_2356543307
3100'

**Comment by halimali** [comment]
Please checkout the develop branchout that resolve it.

**Comment by marceloanabuki** [comment]
返事ありがとう。直してくれた。
