### ISSUE TITLE
Redmine1.1.2でActionView::TemplateError が発生する

### ISSUE THREAD

**Issue by tenten0213** [kawasima/redmine_impasse#158]
以下の 環境でimpasseを入れたところ、プロジェクトの設定画面を開けなくなりました。

impasse 1.2.2
Redmine 1.1.2
Rails 2.3.9
Ruby 1.8.7-p249-i386-mingw32

vendor/plugins/redmine_impasse/app/views/impasse_settings/_form.html.erb　に
以下の一行を追加したところ動きましたので問題ないですが、報告までに。

`<% self.class.send(:include, ImpasseSettingsHelper) -%>`
### エラーログ

```
ActionView::TemplateError (undefined local variable or method `impasse_custom_fields_tabs' for #<ActionView::Base:0x66deee8>) on line #8 of vendor/plugins/redmine_impasse/app/views/impasse_settings/_form.html.erb:
5: </div>
6: <% unless @custom_fields_by_type.empty? %>
7:   <fieldset class="box" id="impasse_custom_fields"><legend><%=l(:label_custom_field_plural)%></legend>
8:     <% impasse_custom_fields_tabs[].each do |tab| %>
9:       <% if @custom_fields_by_type[tab[:name]] %>
10:     <h3><%= l(tab[:label])%></h3>
11:     <div>

    vendor/plugins/redmine_impasse/app/views/impasse_settings/_form.html.erb:8
    vendor/plugins/redmine_impasse/app/views/impasse_settings/_show.html.erb:16
    app/helpers/application_helper.rb:756:in `labelled_tabular_form_for'
    vendor/plugins/redmine_impasse/app/views/impasse_settings/_show.html.erb:13
    app/views/common/_tabs.rhtml:24:in `_run_rhtml_app47views47common47_tabs46rhtml_locals_object_tabs'
    app/views/common/_tabs.rhtml:23:in `each'
    app/views/common/_tabs.rhtml:23:in `_run_rhtml_app47views47common47_tabs46rhtml_locals_object_tabs'
    app/helpers/application_helper.rb:204:in `render_tabs'
    app/views/projects/settings.rhtml:3:in `_run_rhtml_app47views47projects47settings46rhtml'

Rendering C:/Program Files/BitNami Redmine Stack/apps/redmine/public/500.html (500 Internal Server Error)
```

**Comment by k-minemoto** [comment]
下記環境で試しましたが、再現できませんでした。

再現待ちとしてよいですか？＞kawasima

検証環境
- impasse 1.2.2 (develop branch)
- Redmine 1.1.2
- Rails 2.3.9
- Ruby jruby 1.6.5 (ruby-1.8.7-p330)
- OS Windows7(32bit)

確認内容
1. 各プロジェクトの設定
　・[設定]タブを押す
　・[モジュール]サブタブを押し、「テストマネジメント」にチェックがあることを確認
　・[テストマネジメント]サブタブを押す。問題なく開くことを確認
　・ 同画面で「保存」を押す。問題なく設定が保存されることを確認
2. テストケースをいくつか追加する
　・[テスト]タブを押し、いくつかのテストスイート、テストケースを追加する
　・その状態で、もう一度 1. の手順を試す。問題が発生しないことを確認
3. カスタムフィールドを追加する
　・[管理] - [プラグイン] - [Redmine Impasse pluginの設定] - [カスタムフィールド]を押す
　・[テストケース]、[テストスイート]、[テスト計画]、[テスト実行]で、それぞれフィールドを追加する
　・プロジェクトの[設定]タブから[テストマネジメント]サブタブを押す。問題なく開くことを確認
　・テストケース等を追加し、もう一度 1. の手順を試す。問題が発生しないことを確認

**Comment by thijssimonis** [comment]
English?

**Comment by devdiva** [comment]
According to Google Translate the above reads:

I tried the following environment, I could not be reproduced.

Are you waiting for a good reproduction? > Kawasima

Verification environment

```
 impasse 1.2.2 (develop branch)
 Redmine 1.1.2
 Rails 2.3.9
 Ruby jruby 1.6.5 (ruby-1.8.7-p330)
 OS Windows7 (32bit)
```

What to check
One set for each project.
• Press the Settings tab
• Confirm by pressing the [modules] subtab, there is a check in the "Test Management"
• Press the [Test Management subtab. Ensure that the open without any problems
• Press the "Save" in the same screen. Verify that the settings are saved without any problems
Add some 2. Test case
• Press the Test tab, and then add some test suites, test cases
-In this state, try these steps: 1. Again. Make sure that the problem does not occur
3 Add. Custom field
· Administration - press the Custom Field Settings - Redmine Impasse plugin] - [Plug-ins]
· [Test case], [test suite], Test Plan, and in the test run, and then add the respective fields
• Press the [Test Management sub-tab of the project from the Settings tab. Ensure that the open without any problems
• Add and test cases, try these steps: 1. Again. Make sure that the problem does not occur

**Comment by kawasima** [comment]
It's a problem in some environments.

```
ActionView::TemplateError (undefined local variable or method `impasse_custom_fields_tabs' for #<ActionView::Base:0x66deee8>) on line #8 of vendor/plugins/redmine_impasse/app/views/impasse_settings/_form.html.erb:
```

I think this error doesn't occurs in a specific version but it's affected by other plugins or operations.
I’ll try to add "include ImpasseSettingsHelper" explicitly.

**Comment by cforce** [comment]
I tried master and develop branch, the error still there.
Raises when navigating in project settings.

Rendered projects/settings.html.erb within layouts/base (3351.0ms)
Completed 500 Internal Server Error in 3423ms

ActionView::Template::Error (undefined local variable or method `impasse_custom_fields_tabs' for #<#<Class:0x1cb73f8>:0x403289>):
    5: </div>
    6: <% unless @custom_fields_by_type.empty? %>
    7:   <fieldset class="box" id="impasse_custom_fields"><legend><%=l(:label_custom_field_plural)%></legend>
    8:     <% impasse_custom_fields_tabs.each do |tab| %>
    9:       <% if @custom_fields_by_type[tab[:name]] %>
    10:     <h3><%= l(tab[:label])%></h3>
    11:     <div>
  app/helpers/application_helper.rb:977:in`labelled_form_for'
  app/views/common/_tabs.html.erb:24:in `_app_views_common__tabs_html_erb__2082272217_19122'
  app/views/common/_tabs.html.erb:23:in`_app_views_common__tabs_html_erb__2082272217_19122'
  app/helpers/application_helper.rb:259:in `render_tabs'
  app/views/projects/settings.html.erb:3:in`_app_views_projects_settings_html_erb___2027251586_59296'

**Comment by mindo** [comment]
cforce, this is corrected on hotfix/1.2.3 I was also having problems with this and completely missed it.
howto make it work:

$ git clone <project url>
$ git branch -a     (this will show you all branches, including remotes)
$ git checkout remotes/origin/hotfix/1.2.3
