### ISSUE TITLE
english Documentation / Manual

### ISSUE THREAD

**Issue by cforce** [kawasima/redmine_impasse#164]
The plugin is a really great enhancement to redmine.
However its already sohisticated and no more self explaining.
It would be very usful to have an user manual explaining in common what the mental model ist and the main use cases to be able to perform. Furthermore how its dealing which redmine issues, and other entity realtion to other redmine features.

Tx a lot for ur work.

**Comment by cforce** [comment]
ahh ..found it. Its somehow hidden.

http://kawasima.github.com/redmine_impasse/user_manual.html

Please a a link in github readme.rdoc ( already added link to github wiki page) and redmine plugins page.

**Comment by kawasima** [comment]
Thank you for your advice. I adopted your request in hotfix/1.2.3 branch.
