### ISSUE TITLE
[BUG] RecordNotFound (Couldn't find Impasse::TestSuite with id=20)

### ISSUE THREAD

**Issue by cforce** [kawasima/redmine_impasse#174]
Started GET "/projects/myproject/impasse/test_case/show?node%5Bid%5D=20" for 172.25.252.99 at 2012-12-21 12:53:28 +0100
Processing by ImpasseTestCaseController#show as _/_
  Parameters: {"node"=>{"id"=>"20"}, "project_id"=>"myproject"}
  Current user: 00001276 (id=3)
DEPRECATION WARNING: Calling set_table_name is deprecated. Please use `self.table_name = 'the_name'` instead. (called from TestSuite at /home/myuser/redmine/plugins/redmine_impasse/app/models/impasse/test_suite.rb:4)
Completed 500 Internal Server Error in 77ms

ActiveRecord::RecordNotFound (Couldn't find Impasse::TestSuite with id=20):
  activerecord (3.2.8) lib/active_record/relation/finder_methods.rb:341:in `find_one'
  activerecord (3.2.8) lib/active_record/relation/finder_methods.rb:312:in`find_with_ids'
  activerecord (3.2.8) lib/active_record/relation/finder_methods.rb:107:in `find'
  plugins/question_plugin/lib/question_active_record_relation_patch.rb:31:in`find'
  org/jruby/RubyBasicObject.java:1673:in `__send__'
  activerecord (3.2.8) lib/active_record/querying.rb:5:in`find'
  plugins/redmine_impasse/app/controllers/impasse_test_case_controller.rb:288:in `get_node'
  plugins/redmine_impasse/app/controllers/impasse_test_case_controller.rb:36:in`show'
  org/jruby/RubyBasicObject.java:1667:in `__send__'
  org/jruby/RubyKernel.java:2077:in`send'
  actionpack (3.2.8) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.2.8) lib/abstract_controller/base.rb:167:in`process_action'
  actionpack (3.2.8) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.8) lib/abstract_controller/callbacks.rb:18:in`process_action'
  activesupport (3.2.8) lib/active_support/callbacks.rb:494:in `_run__330250672__process_action__999557222__callbacks'
  org/jruby/RubyBasicObject.java:1667:in`**send**'
  org/jruby/RubyKernel.java:2077:in `send'
  activesupport (3.2.8) lib/active_support/callbacks.rb:405:in`**run_callback'
  activesupport (3.2.8) lib/active_support/callbacks.rb:390:in `_run_process_action_callbacks'
  org/jruby/RubyBasicObject.java:1673:in`__send**'
  org/jruby/RubyKernel.java:2081:in `send'
  activesupport (3.2.8) lib/active_support/callbacks.rb:81:in`run_callbacks'
  actionpack (3.2.8) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.8) lib/action_controller/metal/rescue.rb:29:in`process_action'
  actionpack (3.2.8) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  activesupport (3.2.8) lib/active_support/notifications.rb:123:in`instrument'
  activesupport (3.2.8) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.8) lib/active_support/notifications/instrumenter.rb:19:in`instrument'
  activesupport (3.2.8) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.8) lib/action_controller/metal/instrumentation.rb:29:in`process_action'
  actionpack (3.2.8) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  activerecord (3.2.8) lib/active_record/railties/controller_runtime.rb:18:in`process_action'
  actionpack (3.2.8) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.8) lib/abstract_controller/rendering.rb:45:in`process'
  actionpack (3.2.8) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.8) lib/action_controller/metal/rack_delegation.rb:14:in`dispatch'
  actionpack (3.2.8) lib/action_controller/metal.rb:246:in `action'
  org/jruby/RubyProc.java:249:in`call'
  actionpack (3.2.8) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.8) lib/action_dispatch/routing/route_set.rb:36:in`call'
  journey (1.0.4) lib/journey/router.rb:68:in `call'
  org/jruby/RubyArray.java:1612:in`each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.8) lib/action_dispatch/routing/route_set.rb:600:in`call'
  rack-openid (1.3.1) lib/rack/openid.rb:98:in `call'
  actionpack (3.2.8) lib/action_dispatch/middleware/best_standards_support.rb:17:in`call'
  rack (1.4.1) lib/rack/etag.rb:23:in `call'
  rack (1.4.1) lib/rack/conditionalget.rb:25:in`call'
  actionpack (3.2.8) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.8) lib/action_dispatch/middleware/params_parser.rb:21:in`call'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/no_parse.rb:33:in `call'
  actionpack (3.2.8) lib/action_dispatch/middleware/flash.rb:242:in`call'
  rack (1.4.1) lib/rack/session/abstract/id.rb:205:in `context'
  rack (1.4.1) lib/rack/session/abstract/id.rb:200:in`call'
  actionpack (3.2.8) lib/action_dispatch/middleware/cookies.rb:339:in `call'
  activerecord (3.2.8) lib/active_record/query_cache.rb:64:in`call'
  activerecord (3.2.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:473:in `call'
  actionpack (3.2.8) lib/action_dispatch/middleware/callbacks.rb:28:in`call'
  activesupport (3.2.8) lib/active_support/callbacks.rb:408:in `_run__476573025__call__24537021__callbacks'
  org/jruby/RubyBasicObject.java:1667:in`**send**'
  org/jruby/RubyKernel.java:2077:in `send'
  activesupport (3.2.8) lib/active_support/callbacks.rb:405:in`**run_callback'
  activesupport (3.2.8) lib/active_support/callbacks.rb:390:in `_run_call_callbacks'
  org/jruby/RubyBasicObject.java:1667:in`__send**'
  org/jruby/RubyKernel.java:2077:in `send'
  activesupport (3.2.8) lib/active_support/callbacks.rb:81:in`run_callbacks'
  actionpack (3.2.8) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.8) lib/action_dispatch/middleware/remote_ip.rb:31:in`call'
  actionpack (3.2.8) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.8) lib/action_dispatch/middleware/show_exceptions.rb:56:in`call'
  railties (3.2.8) lib/rails/rack/logger.rb:26:in `call_app'
  railties (3.2.8) lib/rails/rack/logger.rb:16:in`call'
  actionpack (3.2.8) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.1) lib/rack/methodoverride.rb:21:in`call'
  rack (1.4.1) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.8) lib/active_support/cache/strategy/local_cache.rb:72:in`call'
  rack (1.4.1) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.8) lib/action_dispatch/middleware/static.rb:62:in`call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in`fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in`call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.8) lib/rails/engine.rb:479:in`call'
  railties (3.2.8) lib/rails/application.rb:223:in `call'
  rack (1.4.1) lib/rack/content_length.rb:14:in`call'
  railties (3.2.8) lib/rails/rack/log_tailer.rb:17:in `call'
  rack (1.4.1) lib/rack/handler/webrick.rb:59:in`service'
  /home/myuser/.rvm/rubies/jruby-1.7.0/lib/ruby/1.9/webrick/httpserver.rb:138:in `service'
  /home/myuser/.rvm/rubies/jruby-1.7.0/lib/ruby/1.9/webrick/httpserver.rb:94:in`run'
  /home/myuser/.rvm/rubies/jruby-1.7.0/lib/ruby/1.9/webrick/httpserver.rb:72:in `run'
  /home/myuser/.rvm/rubies/jruby-1.7.0/lib/ruby/1.9/webrick/server.rb:191:in`start_thread'
  /home/myuser/.rvm/rubies/jruby-1.7.0/lib/ruby/1.9/webrick/server.rb:181:in `start_thread'

Started GET "/projects/myproject/impasse/test_case/show?node%5Bid%5D=20" for 172.25.252.99 at 2012-12-21 12:53:54 +0100
Processing by ImpasseTestCaseController#show as _/_
  Parameters: {"node"=>{"id"=>"20"}, "project_id"=>"myproject"}
  Current user: 00001276 (id=3)
Completed 500 Internal Server Error in 24ms

ActiveRecord::RecordNotFound (Couldn't find Impasse::TestSuite with id=20):
  activerecord (3.2.8) lib/active_record/relation/finder_methods.rb:341:in `find_one'
  activerecord

**Comment by AndreMiras** [comment]
Fixed in https://github.com/cforce/redmine_impasse/pull/11
