### ISSUE TITLE
プロジェクト名が識別子と異なるプロジェクトでテストケースが表示されない

### ISSUE THREAD

**Issue by komi** [kawasima/redmine_impasse#30]
Redmineのプロジェクト名が識別子と異なるプロジェクトで
Impasseの「テスト」画面を開いた場合、テストスイート、ケースのツリーが表示されませんでした。
同じプロジェクトで、Redmineのプロジェクト名を識別子と同じにすると、問題は解消されました。
お手数おかけしますが、ご確認いただけますでしょうか。

なお、このときサーバ側には以下のようなエラーが出ていました。
//////////
RuntimeError (Called id for nil, which would mistakenly be 4 -- if you really wanted the id of nil,
use object_id):
  vendor/plugins/redmine_impasse/app/controllers/impasse/test_case_controller.rb:17:in `list'
（以下略）
//////////

※以下ご参考になるかわかりませんが
コード上はテスト画面のrootのnodeを「@project.identifier」を元に取得しようとしているようにみえましたが、
impasse_nodesテーブルのnameカラムにはprojectsテーブルのnameカラムと同じ値が保存されていました。

**Comment by kawasima** [comment]
@project.nameでは一意にならないので、@project.identifierに揃えます。今回の件はその対応やったときの修正漏れかと思います。
既存のプロジェクトはimpasse_nodesテーブルのルートノード名をidentifierにUPDATEしてください。
