### ISSUE TITLE
Could it support the redmine 2.X?

### ISSUE THREAD

**Issue by archonwang** [kawasima/redmine_impasse#45]
Could it support the redmine 2.X  with rails 3.2.5? 

Thanks.

**Comment by kawasima** [comment]
Thank you for your interest.
I'm going to support the redmine 2.x at the next milestone.

**Comment by kawasima** [comment]
I've finished with it at the version 1.1

**Comment by archonwang** [comment]
Hi，Yoshitaka Kawashima

Great！！

I will  test it ASAP. Thanks so much.

2012-07-16    09:44:42
Steven.W

From: Yoshitaka Kawashima
Date: 2012-07-16 09:29
To: Steven.W
Subject: Re: [redmine_impasse] Could it support the redmine 2.X? (#45)
I've finished with it at the version 1.1

---

**Comment by leaving** [comment]
I tried impass V1.1.0 with redmine 2.0.3, but i failed!

I will try again, and post the errors.
