### ISSUE TITLE
【不具合】テストケースを削除しようとするとInternal Server Error

### ISSUE THREAD

**Issue by komi** [kawasima/redmine_impasse#47]
Processing Impasse::TestCaseController#destroyで、以下のエラーが出ていました。

NoMethodError (undefined method `count_by_test_case_id' for #<Class:0x1edca208>):
  vendor/plugins/redmine_impasse/app/controllers/impasse/test_case_controller.rb:153:in`destroy'

**Comment by kawasima** [comment]
count_by_xxx が redmine 1.2.x以下のRailsだと使えないので発生しています。
redmine1.1.x以上をサポート対象にしたいので、対応します。

**Comment by komi** [comment]
ご確認ありがとうございます。
ご参考までに、本事象はRedmine 1.3.3.stableで確認済です。

**Comment by kawasima** [comment]
Version1.1で修正済み
