### ISSUE TITLE
【不具合】テストスイート、テストケースの名称に含まれる実体参照が保存後に変換されて表示される

### ISSUE THREAD

**Issue by komi** [kawasima/redmine_impasse#53]
実体参照（& #34;　& amp;　※＆の後のスペースは実際にはありません）を入力して保存、編集画面（子画面）を開くと、変換されて「"　&」で表示されました。
値を変えずにそのまま「更新」ボタンを押下すると変換後の値で保存されます。
なお、ツリー画面に表示されるタイトルは変換されずにそのまま「&#34;　&amp;」で表示されるので、こちらは想定通りの動きと思います。

**Comment by k-minemoto** [comment]
developブランチで確認しましたが、再現しないのでCloseします。
