### ISSUE TITLE
Error with charset

### ISSUE THREAD

**Issue by AlDemion** [kawasima/redmine_impasse#75]
When i try to create Testplan i got 

Processing by ImpasseTestPlansController#show as HTML
  Parameters: {"project_id"=>"test-qa", "id"=>"1"}
  Rendered plugins/redmine_impasse/app/views/impasse_common/_impasse_tabs.html.erb (2.7ms)
DEPRECATION WARNING: :confirm option is deprecated and will be removed from Rails 4.0. Use ':data => { :confirm => 'Text' }' instead. (called from link_to_if_authorized at /usr/share/redmine/app/helpers/application_helper.rb:43)
  Rendered plugins/redmine_impasse/app/views/impasse_test_plans/show.html.erb within layouts/base (7.7ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_html_header.html.erb (1.5ms)
Completed 500 Internal Server Error in 209ms

ActionView::Template::Error (incompatible character encodings: UTF-8 and ASCII-8BIT):
    61:         <%= yield :sidebar %>
    62:         <%= view_layouts_base_sidebar_hook_response %>
    63:     </div>
    64:
    65:     <div id="content">
    66:         <%= render_flash_messages %>
    67:         <%= yield %>
  app/views/layouts/base.html.erb:64:in `_app_views_layouts_base_html_erb__4352778674256341208_39066460'

**Comment by kawasima** [comment]
It looks like the issue #81. I fixed it in the version 1.1.1.
