### ISSUE TITLE
Test caseのステップで「期待する結果」の値が空の場合、エラーが発生する。

### ISSUE THREAD

**Issue by naitoh** [kawasima/redmine_impasse#76]
CentOS 6.0 x86, impasse v1.1.0, Redmein 1.3.1, MySQL 5.1, Ruby 1.8.7 で確認しました。

Test case の作成および更新で、「ステップ」に add ボタンを押した場合、

1.「期待する結果」「期待する結果」が二つあり、何か違和感がします。「手順」「期待する結果」などが適当ではないでしょうか？
2. 「期待する結果」を両方埋めないと「Cann't connect. reason internal server error」が発生します。なお、入力必須を意味する「*」の文字はありません。

エラーログは下記。

<pre>
Processing Impasse::TestCaseController#edit to json (for 192.168.56.1 at 2012-07-13 10:09:28) [POST]
  Parameters: {"format"=>"json", "node"=>{"name"=>"c", "id"=>"14", "parent_id"=>"2", "node_order"=>"0"}, "project_id"=>"aa", "node_type"=>"test_case", "action"=>"edit", "authenticity_token"=>"tEx0rN0LNxhNs/mujcELQzcihZFimZ2wUzSKL3jWadg=", "undefined"=>"3", "node_keywords"=>"", "controller"=>"impasse/test_case", "test_steps"=>{"1"=>{"actions"=>"", "expected_results"=>"", "step_number"=>"1"}}, "test_case"=>{"importance"=>"1", "summary"=>"", "preconditions"=>""}}

ArgumentError (wrong number of arguments (0 for 1)):
  vendor/plugins/redmine_impasse/app/controllers/impasse/test_case_controller.rb:106:in `initialize'
  vendor/plugins/redmine_impasse/app/controllers/impasse/test_case_controller.rb:106:in `exception'
  vendor/plugins/redmine_impasse/app/controllers/impasse/test_case_controller.rb:106:in `raise'
  vendor/plugins/redmine_impasse/app/controllers/impasse/test_case_controller.rb:106:in `edit'
  passenger (3.0.8) lib/phusion_passenger/rack/request_handler.rb:96:in `process_request'
  passenger (3.0.8) lib/phusion_passenger/abstract_request_handler.rb:513:in `accept_and_process_next_request'
  passenger (3.0.8) lib/phusion_passenger/abstract_request_handler.rb:274:in `main_loop'
  passenger (3.0.8) lib/phusion_passenger/classic_rails/application_spawner.rb:321:in `start_request_handler'
  passenger (3.0.8) lib/phusion_passenger/classic_rails/application_spawner.rb:275:in `send'
  passenger (3.0.8) lib/phusion_passenger/classic_rails/application_spawner.rb:275:in `handle_spawn_application'
  passenger (3.0.8) lib/phusion_passenger/utils.rb:479:in `safe_fork'
  passenger (3.0.8) lib/phusion_passenger/classic_rails/application_spawner.rb:270:in `handle_spawn_application'
  passenger (3.0.8) lib/phusion_passenger/abstract_server.rb:357:in `__send__'
  passenger (3.0.8) lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
  passenger (3.0.8) lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
  passenger (3.0.8) lib/phusion_passenger/abstract_server.rb:180:in `start'
  passenger (3.0.8) lib/phusion_passenger/classic_rails/application_spawner.rb:149:in `start'
  passenger (3.0.8) lib/phusion_passenger/spawn_manager.rb:219:in `spawn_rails_application'
  passenger (3.0.8) lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
  passenger (3.0.8) lib/phusion_passenger/spawn_manager.rb:214:in `spawn_rails_application'
  passenger (3.0.8) lib/phusion_passenger/abstract_server_collection.rb:82:in `synchronize'
  passenger (3.0.8) lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
  passenger (3.0.8) lib/phusion_passenger/spawn_manager.rb:213:in `spawn_rails_application'
  passenger (3.0.8) lib/phusion_passenger/spawn_manager.rb:132:in `spawn_application'
  passenger (3.0.8) lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
  passenger (3.0.8) lib/phusion_passenger/abstract_server.rb:357:in `__send__'
  passenger (3.0.8) lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
  passenger (3.0.8) lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
  passenger (3.0.8) helper-scripts/passenger-spawn-server:99

Rendering /opt/Redmine/redmine.d/redmine-1.3.1/public/500.html (500 Internal Server Error)
</pre>

**Comment by kawasima** [comment]
ありがとうございます。バリデーションのメッセージがうまく取り出せてませんでした。
その他修正したものをv1.1.1としてリリースしてますのでご確認ください！

**Comment by naitoh** [comment]
修正されています。ありがとうございました！
