### ISSUE TITLE
redmine 1.2.2 compatibility issue 

### ISSUE THREAD

**Issue by albert-mirzoyan** [kawasima/redmine_impasse#79]
Please make the plugin fully compatible with red-mine 1.2
Ajax requests are failing when there is a user or a date assigned to case.

I just removed formatting code and it worked for me.

Processing ImpasseExecutionsController#get_list (for 212.73.74.28 at 2012-07-17 18:39:57) [GET]
  Parameters: {"prefix"=>"plan", "project_id"=>"test-project", "controller"=>"impasse_executions", "id"=>"-1", "action"=>"get_list", "test_plan_id"=>"1"}

NoMethodError (undefined method `name_formatter' for #<Class:0xb673579c>):
  vendor/plugins/redmine_impasse/app/controllers/impasse_executions_controller.rb:188:in`convert'
  vendor/plugins/redmine_impasse/app/controllers/impasse_executions_controller.rb:175:in `each'
  vendor/plugins/redmine_impasse/app/controllers/impasse_executions_controller.rb:175:in`convert'
  vendor/plugins/redmine_impasse/app/controllers/impasse_executions_controller.rb:135:in `get_list'
###### 

Processing ImpasseExecutionsController#get_list (for 192.168.2.125 at 2012-07-17 19:43:22) [GET]
  Parameters: {"prefix"=>"plan", "project_id"=>"test-project", "controller"=>"impasse_executions", "id"=>"-1", "action"=>"get_list", "test_plan_id"=>"2"}

NoMethodError (undefined method `strftime' for "2012-08-22":String):
  lib/redmine/i18n.rb:40:in`format_date'
  vendor/plugins/redmine_impasse/app/controllers/impasse_executions_controller.rb:191:in `convert'
  vendor/plugins/redmine_impasse/app/controllers/impasse_executions_controller.rb:175:in`each'
  vendor/plugins/redmine_impasse/app/controllers/impasse_executions_controller.rb:175:in `convert'
  vendor/plugins/redmine_impasse/app/controllers/impasse_executions_controller.rb:135:in`get_list'

**Comment by kawasima** [comment]
Thank you for letting me know. 
the name_fomatter is available since 1.3.x or later. And when global data format is set, NoMethodErro occurs.

I'll fix it in the next bugfix version 1.1.1

**Comment by albert-mirzoyan** [comment]
the fix is validated.
thank you
