### ISSUE TITLE
Ruby 1.9 Compatibility Issues

### ISSUE THREAD

**Issue by dkmorgan** [kawasima/redmine_impasse#81]
I cannot seem to get the plugin working with my environment:

Windows Server 2008
Redmine： 2.0.2
Java JDK： 1.6.0_31
MySQL Community Edition： 5.5.23
Torquebox： 2.0.3
  JBoss AS： 7.1.1.Final
  JRuby： 1.6.7.2 (Ruby 1.9 Mode)

I get the following error when creating a new Test Plan:

```
  Rendered plugins/redmine_impasse/app/views/impasse_test_plans/tc_assign.html.erb within layouts/base (266.0ms)
Completed 500 Internal Server Error in 733ms

ActionView::Template::Error (incompatible character encodings: UTF-8 and ASCII-8BIT):
    26:     </script>
    27: <% end %>
    28: 
    29: <%= impasse_breadcrumb [
    30:     link_to(l(:label_impasse), {:controller => :impasse_test_case, :action => :index, :project_id => @project}),
    31:     link_to(l(:label_test_plans_list), {:controller => :impasse_test_plans, :action => :index, :project_id => @project})
    32: ]%>
```

**Comment by kawasima** [comment]
I added magic comment to helper files. In my environment (jruby 1.6.7 on ubuntu 12.04), the error no longer occurred.
Can you check it in the version 1.1.1?

**Comment by dkmorgan** [comment]
I checked version 1.1.1 and the issue has been fixed.
Thank you very much for the quick action!
