### ISSUE TITLE
No table created with migrated in  redmine 2.03

### ISSUE THREAD

**Issue by leaving** [kawasima/redmine_impasse#99]
I  installed redmine V1.1.1 with "rake redmine:plugins:migrate RAILS_ENV=production", but no table created in mysql;
When i create a new project with impasse module, i got the message in server log:

Started GET "/projects/test2/settings" for 192.168.2.1 at 2012-08-06 03:42:21 +0000
Processing by ProjectsController#settings as HTML
  Parameters: {"id"=>"test2"}
  Rendered projects/_form.html.erb (20.0ms)
  Rendered projects/_edit.html.erb (20.0ms)
  Rendered projects/settings/_modules.html.erb (10.0ms)
  Rendered projects/settings/_members.html.erb (100.0ms)
  Rendered projects/settings/_versions.html.erb (10.0ms)
  Rendered projects/settings/_issue_categories.html.erb (0.0ms)
  Rendered projects/settings/_wiki.html.erb (10.0ms)
  Rendered projects/settings/_repositories.html.erb (10.0ms)
  Rendered projects/settings/_boards.html.erb (10.0ms)
DEPRECATION WARNING: :confirm option is deprecated and will be removed from Rails 4.0. Use ':data => { :confirm => 'Text' }' instead. (called from block in _app_views_projects_settings__activities_html_erb__71682825_86385010 at /home/wuyan/server/redmine-2.0.3/app/views/projects/settings/_activities.html.erb:35)
  Rendered projects/settings/_activities.html.erb (10.0ms)
  Rendered common/_tabs.html.erb (220.0ms)
  Rendered projects/settings.html.erb within layouts/base (220.0ms)
Completed 500 Internal Server Error in 250ms

ActionView::Template::Error (Missing partial impasse_settings/show with {:locale=>[:en], :formats=>[:html], :handlers=>[:erb, :builder, :rsb, :rjs]}. Searched in:
- "/home/wuyan/server/redmine-2.0.3/app/views"
  ):
  21: </script>
  22: 
  23: <% tabs.each do |tab| -%>
  24:   <%= content_tag('div', render(:partial => tab[:partial], :locals => {:tab => tab} ),
  25:                        :id => "tab-content-#{tab[:name]}",
  26:                        :style => (tab[:name] != selected_tab ? 'display:none' : nil),
  27:                        :class => 'tab-content') %>
  app/views/common/_tabs.html.erb:24:in `block in _app_views_common__tabs_html_erb__606463089_87083080'
  app/views/common/_tabs.html.erb:23:in`each'
  app/views/common/_tabs.html.erb:23:in `_app_views_common__tabs_html_erb__606463089_87083080'
  app/helpers/application_helper.rb:231:in`render_tabs'
  app/views/projects/settings.html.erb:3:in `_app_views_projects_settings_html_erb___183236903_87072510'

List My enviroment  blow:

wuyan@debian:~/server/redmine-2.0.3/plugins/impasse/db$ ruby -v
ruby 1.9.3p194 (2012-04-20 revision 35410) [i686-linux]
wuyan@debian:~/server/redmine-2.0.3/plugins/impasse/db$ rails -v
Rails 3.2.6
wuyan@debian:~/server/redmine-2.0.3/plugins/impasse/db$ gem list

**\* LOCAL GEMS ***

actionmailer (3.2.6)
actionpack (3.2.6)
activemodel (3.2.6)
activerecord (3.2.6)
activeresource (3.2.6)
activesupport (3.2.6)
arel (3.0.2)
builder (3.0.0)
bundler (1.1.5)
coderay (1.0.7)
coffee-rails (3.2.2)
coffee-script (2.2.0)
coffee-script-source (1.3.3)
erubis (2.7.0)
execjs (1.4.0)
hike (1.2.1)
i18n (0.6.0)
journey (1.0.4)
jquery-rails (2.0.2)
json (1.7.4, 1.7.3)
libv8 (3.3.10.4 x86-linux)
mail (2.4.4)
mime-types (1.19)
multi_json (1.3.6)
mysql2 (0.3.11)
net-ldap (0.3.1)
polyglot (0.3.3)
prototype-rails (3.2.1)
rack (1.4.1)
rack-cache (1.2)
rack-openid (1.3.1)
rack-ssl (1.3.2)
rack-test (0.6.1)
rails (3.2.6)
railties (3.2.6)
rake (0.9.2.2)
rdoc (3.12)
ruby-openid (2.1.8)
rubygems-bundler (1.0.3)
rvm (1.11.3.5)
sass (3.1.20)
sass-rails (3.2.5)
sprockets (2.1.3)
sqlite3 (1.3.6)
therubyracer (0.10.1)
thor (0.15.4)
tilt (1.3.3)
treetop (1.4.10)
tzinfo (0.3.33)
uglifier (1.2.6)

BTW: If i move the migrates into other plugins, then i can see the creating table message;

**Comment by kawasima** [comment]
Where did you install the Impasse? Because missing template occurred, it looks like install failed.

**Comment by leaving** [comment]
I installed in redmine-2.0.3/plugins:

wuyan@debian:~/server/redmine-2.0.3$ ls  plugins -l
total 328
drwxr-xr-x 11 wuyan wuyan   4096 Aug  4 11:44 impasse
-rw-r--r--  1 wuyan wuyan 322587 Aug  1 06:49 impasse.tar.gz
-rw-r--r--  1 wuyan wuyan     31 Jun 18 20:21 README
wuyan@debian:~/server/redmine-2.0.3$

**Comment by kawasima** [comment]
Please try to rename the install directory to "redmine_impasse".

**Comment by leaving** [comment]
That's ok! Thanks very much!
